using UnityEngine;

public  enum SoundType{
    KapiAc,
    KapiKapat,
    AyakSesi,
    SayfaCevir
}

[RequireComponent(typeof(AudioSource))]
public class SoundManager : MonoBehaviour
{
    [SerializeField] private AudioClip[] soundList;
    private static SoundManager instance;
    private AudioSource audioSource;
    // Start is called once before the first execution of Update after the MonoBehaviour is created
    void Awake(){
        instance = this;
    }
    void Start()
    {
        audioSource = GetComponent<AudioSource>();
    }

    // Update is called once per frame
    void Update()
    {
        
    }

    public static void PlaySound(SoundType sound, float volume = 1){
        instance.audioSource.PlayOneShot(instance.soundList[(int)sound],volume);
    }
}
